In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer, KNNImputer
import glob
import os

In [3]:
#get a list of file paths to all .csv files it finds.
path = os.path.expanduser("Input/Dataset_v2.csv") 

# glob.glob now looks for the file directly inside AutoPrepAI
csv_files = glob.glob(path)
# csv_files = glob.glob("/Graduation project/AutoPrepAI/*.csv", recursive=True)
if not csv_files:
    raise Exception("no CSV found under //input. add data and rerun")
DATA_PATH = csv_files[0] #picks the first one to work with
print("Using dataset:", DATA_PATH)
dataframe = pd.read_csv(DATA_PATH)
dataframe.head()   #shows the first 5 rows

Using dataset: Input/Dataset_v2.csv

   id   age         salary department  years_experience  performance_score
0   1  39.0   70990.331549  Marketing               9.0           2.314233
1   2  33.0   63869.505244  Marketing               4.0                NaN
2   3   NaN   50894.455549  Marketing              11.0           1.729832
3   4  50.0  402959.483344      Sales               3.0           4.860839
4   5  32.0            NaN    Finance               3.0           2.712736

In [4]:
#data size(rows,coloumn)
print("Shape:", dataframe.shape)
#check for missing value and return set with same size but true in missing values else false ;isna;
print("\nMissing values per column:\n", dataframe.isna().sum())

Shape: (1001, 6)

Missing values per column:
 id                    0
age                  50
salary               50
department            0
years_experience     50
performance_score    51
dtype: int64

In [5]:
numerical_cols = dataframe.select_dtypes(include=[np.number]).columns.tolist()
non_numerical = [c for c in dataframe.columns if c not in numerical_cols]
print("The numerical columns:", numerical_cols)
print("the categorical columns:", non_numerical)

The numerical columns: ['id', 'age', 'salary', 'years_experience', 'performance_score']
the categorical columns: ['department']

In [6]:
if numerical_cols:
    imputer_mean = SimpleImputer(strategy="mean")
    dataframe_mean = dataframe.copy() #copy of dataframe to leave the original one unchanged
    dataframe_mean[numerical_cols] = imputer_mean.fit_transform(dataframe_mean[numerical_cols])
    print("After Mean imputation, missing values (in numeric coloumns):", dataframe_mean[numerical_cols].isna().sum().sum())
    display(dataframe_mean)
else:
    print("not a numeric column.")

After Mean imputation, missing values (in numeric coloumns): 0

,id,age,salary,department,years_experience,performance_score
0,1.0,39.000000,70990.331549,Marketing,9.0,2.314233
1,2.0,33.000000,63869.505244,Marketing,4.0,2.970243
2,3.0,35.164038,50894.455549,Marketing,11.0,1.729832
3,4.0,50.000000,402959.483344,Sales,3.0,4.860839
4,5.0,32.000000,59811.994529,Finance,3.0,2.712736
...,...,...,...,...,...,...
996,997.0,52.000000,59811.994529,Engineering,9.0,1.388073
997,998.0,41.000000,36771.880232,Finance,6.0,1.256954
998,999.0,29.000000,47553.995541,Finance,6.0,3.370784
999,1000.0,40.000000,38826.460328,Engineering,6.0,2.970243
1000,1001.0,58.000000,101000.560000,Marketing,8.0,2.970243

In [7]:
if numerical_cols:
    imputer_median = SimpleImputer(strategy="median")
    dataframe_median = dataframe.copy()
    dataframe_median[numerical_cols] = imputer_median.fit_transform(dataframe_median[numerical_cols])
    print("After Median imputation, missing values (in numeric coloumns):", dataframe_median[numerical_cols].isna().sum().sum())
    display(dataframe_median)
else:
    print("not a numeric columns")

After Median imputation, missing values (in numeric coloumns): 0

,id,age,salary,department,years_experience,performance_score
0,1.0,39.0,70990.331549,Marketing,9.0,2.314233
1,2.0,33.0,63869.505244,Marketing,4.0,2.955539
2,3.0,35.0,50894.455549,Marketing,11.0,1.729832
3,4.0,50.0,402959.483344,Sales,3.0,4.860839
4,5.0,32.0,51236.596294,Finance,3.0,2.712736
...,...,...,...,...,...,...
996,997.0,52.0,51236.596294,Engineering,9.0,1.388073
997,998.0,41.0,36771.880232,Finance,6.0,1.256954
998,999.0,29.0,47553.995541,Finance,6.0,3.370784
999,1000.0,40.0,38826.460328,Engineering,6.0,2.955539
1000,1001.0,58.0,101000.560000,Marketing,8.0,2.955539

In [8]:
imputer_mostfrequent = SimpleImputer(strategy="most_frequent")
dataframe_mostfrequent = dataframe.copy()
cols = numerical_cols + non_numerical
if cols:
    dataframe_mostfrequent[cols] = imputer_mostfrequent.fit_transform(dataframe_mostfrequent[cols])
    print("After Most Frequent imputation, missing values (for all coloumns):", dataframe_mostfrequent.isna().sum().sum())
    display(dataframe_mostfrequent)
else:
    print("please add some coloumns")

After Most Frequent imputation, missing values (for all coloumns): 0

,id,age,salary,department,years_experience,performance_score
0,1,39.0,70990.331549,Marketing,9.0,2.314233
1,2,33.0,63869.505244,Marketing,4.0,1.006575
2,3,35.0,50894.455549,Marketing,11.0,1.729832
3,4,50.0,402959.483344,Sales,3.0,4.860839
4,5,32.0,5894.17048,Finance,3.0,2.712736
...,...,...,...,...,...,...
996,997,52.0,5894.17048,Engineering,9.0,1.388073
997,998,41.0,36771.880232,Finance,6.0,1.256954
998,999,29.0,47553.995541,Finance,6.0,3.370784
999,1000,40.0,38826.460328,Engineering,6.0,1.006575
1000,1001,58.0,101000.56,Marketing,8.0,1.006575

In [9]:
imputer_const = SimpleImputer(strategy="constant", fill_value="missing")
dataframe_const = dataframe.copy()
cols = numerical_cols + non_numerical
if cols:
    dataframe_const[cols] = imputer_const.fit_transform(dataframe_const[cols])
    print("After Constant imputation, missing values:", dataframe_const.isna().sum().sum())
    display(dataframe_const)
else:
    print("No columns to impute.")

After Constant imputation, missing values: 0

,id,age,salary,department,years_experience,performance_score
0,1,39.0,70990.331549,Marketing,9.0,2.314233
1,2,33.0,63869.505244,Marketing,4.0,missing
2,3,missing,50894.455549,Marketing,11.0,1.729832
3,4,50.0,402959.483344,Sales,3.0,4.860839
4,5,32.0,missing,Finance,3.0,2.712736
...,...,...,...,...,...,...
996,997,52.0,missing,Engineering,9.0,1.388073
997,998,41.0,36771.880232,Finance,6.0,1.256954
998,999,29.0,47553.995541,Finance,6.0,3.370784
999,1000,40.0,38826.460328,Engineering,6.0,missing
1000,1001,58.0,101000.56,Marketing,8.0,missing

In [10]:
if numerical_cols:
    from sklearn.impute import KNNImputer
    #fill missing with avg of nearest 3 neighbors
    imputer_knn = KNNImputer(n_neighbors=3)
    dataframe_knn = dataframe.copy()
    dataframe_knn[numerical_cols] = imputer_knn.fit_transform(dataframe_knn[numerical_cols])
    print("After KNN imputation, missing values (numeric):", dataframe_knn[numerical_cols].isna().sum().sum())
    display(dataframe_knn)
else:
    print("nor numeric columns")

After KNN imputation, missing values (numeric): 0

,id,age,salary,department,years_experience,performance_score
0,1.0,39.0,70990.331549,Marketing,9.0,2.314233
1,2.0,33.0,63869.505244,Marketing,4.0,3.572085
2,3.0,38.0,50894.455549,Marketing,11.0,1.729832
3,4.0,50.0,402959.483344,Sales,3.0,4.860839
4,5.0,32.0,61838.358918,Finance,3.0,2.712736
...,...,...,...,...,...,...
996,997.0,52.0,76570.232458,Engineering,9.0,1.388073
997,998.0,41.0,36771.880232,Finance,6.0,1.256954
998,999.0,29.0,47553.995541,Finance,6.0,3.370784
999,1000.0,40.0,38826.460328,Engineering,6.0,3.438434
1000,1001.0,58.0,101000.560000,Marketing,8.0,3.438434

In [11]:
print("Before: \n",dataframe)
print("\n After Mean imputation: \n", dataframe_mean if 'dataframe_mean' in globals() else "N/A")
print("\n After Median imputation: \n", dataframe_median if 'dataframe_median' in globals() else "N/A")
print("\n After Most Frequency imputation: \n", dataframe_mostfrequent if 'dataframe_mostfrequent' in globals() else "N/A")
print("\n After Constant imputation: \n", dataframe_const if 'dataframe_const' in globals() else "N/A")
print("\n After KNN imputation: \n", dataframe_knn if 'dataframe_knn' in globals() else "N/A")

Before:
         id   age         salary   department  years_experience  \
0        1  39.0   70990.331549    Marketing               9.0
1        2  33.0   63869.505244    Marketing               4.0
2        3   NaN   50894.455549    Marketing              11.0
3        4  50.0  402959.483344        Sales               3.0
4        5  32.0            NaN      Finance               3.0
...    ...   ...            ...          ...               ...
996    997  52.0            NaN  Engineering               9.0
997    998  41.0   36771.880232      Finance               6.0
998    999  29.0   47553.995541      Finance               6.0
999   1000  40.0   38826.460328  Engineering               6.0
1000  1001  58.0  101000.560000    Marketing               8.0

      performance_score
0              2.314233
1                   NaN
2              1.729832
3              4.860839
4              2.712736
...                 ...
996            1.388073
997            1.256954
998            3.370784
999                 NaN
1000                NaN

[1001 rows x 6 columns]

 After Mean imputation:
           id        age         salary   department  years_experience  \
0        1.0  39.000000   70990.331549    Marketing               9.0
1        2.0  33.000000   63869.505244    Marketing               4.0
2        3.0  35.164038   50894.455549    Marketing              11.0
3        4.0  50.000000  402959.483344        Sales               3.0
4        5.0  32.000000   59811.994529      Finance               3.0
...      ...        ...            ...          ...               ...
996    997.0  52.000000   59811.994529  Engineering               9.0
997    998.0  41.000000   36771.880232      Finance               6.0
998    999.0  29.000000   47553.995541      Finance               6.0
999   1000.0  40.000000   38826.460328  Engineering               6.0
1000  1001.0  58.000000  101000.560000    Marketing               8.0

      performance_score
0              2.314233
1              2.970243
2              1.729832
3              4.860839
4              2.712736
...                 ...
996            1.388073
997            1.256954
998            3.370784
999            2.970243
1000           2.970243

[1001 rows x 6 columns]

 After Median imputation:
           id   age         salary   department  years_experience  \
0        1.0  39.0   70990.331549    Marketing               9.0
1        2.0  33.0   63869.505244    Marketing               4.0
2        3.0  35.0   50894.455549    Marketing              11.0
3        4.0  50.0  402959.483344        Sales               3.0
4        5.0  32.0   51236.596294      Finance               3.0
...      ...   ...            ...          ...               ...
996    997.0  52.0   51236.596294  Engineering               9.0
997    998.0  41.0   36771.880232      Finance               6.0
998    999.0  29.0   47553.995541      Finance               6.0
999   1000.0  40.0   38826.460328  Engineering               6.0
1000  1001.0  58.0  101000.560000    Marketing               8.0

      performance_score
0              2.314233
1              2.955539
2              1.729832
3              4.860839
4              2.712736
...                 ...
996            1.388073
997            1.256954
998            3.370784
999            2.955539
1000           2.955539

[1001 rows x 6 columns]

 After Most Frequency imputation:
         id   age         salary   department years_experience  \
0        1  39.0   70990.331549    Marketing              9.0
1        2  33.0   63869.505244    Marketing              4.0
2        3  35.0   50894.455549    Marketing             11.0
3        4  50.0  402959.483344        Sales              3.0
4        5  32.0     5894.17048      Finance              3.0
...    ...   ...            ...          ...              ...
996    997  52.0     5894.17048  Engineering              9.0
997    998  41.0   36771.880232      Finance              6.0
998    999  29.0   47553.995541      Finance              6.0
999   1000  40.0   38826.460328  Engineering              6.0
1000  1001  58.0      101000.56    Marketing              8.0

     performance_score
0             2.314233
1             1.006575
2             1.729832
3             4.860839
4             2.712736
...                ...
996           1.388073
997           1.256954
998           3.370784
999           1.006575
1000          1.006575

[1001 rows x 6 columns]

 After Constant imputation:
         id      age         salary   department years_experience  \
0        1     39.0   70990.331549    Marketing              9.0
1        2     33.0   63869.505244    Marketing              4.0
2        3  missing   50894.455549    Marketing             11.0
3        4     50.0  402959.483344        Sales              3.0
4        5     32.0        missing      Finance              3.0
...    ...      ...            ...          ...              ...
996    997     52.0        missing  Engineering              9.0
997    998     41.0   36771.880232      Finance              6.0
998    999     29.0   47553.995541      Finance              6.0
999   1000     40.0   38826.460328  Engineering              6.0
1000  1001     58.0      101000.56    Marketing              8.0

     performance_score
0             2.314233
1              missing
2             1.729832
3             4.860839
4             2.712736
...                ...
996           1.388073
997           1.256954
998           3.370784
999            missing
1000           missing

[1001 rows x 6 columns]

 After KNN imputation:
           id   age         salary   department  years_experience  \
0        1.0  39.0   70990.331549    Marketing               9.0
1        2.0  33.0   63869.505244    Marketing               4.0
2        3.0  38.0   50894.455549    Marketing              11.0
3        4.0  50.0  402959.483344        Sales               3.0
4        5.0  32.0   61838.358918      Finance               3.0
...      ...   ...            ...          ...               ...
996    997.0  52.0   76570.232458  Engineering               9.0
997    998.0  41.0   36771.880232      Finance               6.0
998    999.0  29.0   47553.995541      Finance               6.0
999   1000.0  40.0   38826.460328  Engineering               6.0
1000  1001.0  58.0  101000.560000    Marketing               8.0

      performance_score
0              2.314233
1              3.572085
2              1.729832
3              4.860839
4              2.712736
...                 ...
996            1.388073
997            1.256954
998            3.370784
999            3.438434
1000           3.438434

[1001 rows x 6 columns]